###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
module Baml
  module Inlined
    FILE_MAP = {
        
        "clients.baml" => "client<llm> Claude {\n  provider anthropic\n  options {\n    model \"claude-sonnet-4-6\"\n    api_key env.ANTHROPIC_API_KEY\n  }\n}\n",
        "generators.baml" => "// This helps use auto generate libraries you can use in the language of\n// your choice. You can have multiple generators if you use multiple languages.\n// Just ensure that the output_dir is different for each generator.\ngenerator target {\n    // Valid values: \"python/pydantic\", \"typescript\", \"ruby/sorbet\", \"rest/openapi\"\n    output_type \"ruby/sorbet\"\n\n    // Where the generated code will be saved (relative to baml_src/)\n    output_dir \"../\"\n\n    // The version of the BAML package you have installed (e.g. same version as your baml-py or @boundaryml/baml).\n    // The BAML VSCode extension version should also match this version.\n    version \"0.90.2\"\n}\n",
        "meals.baml" => "function SuggestMeals(\n  profile: UserProfile,\n  flow_type: string,\n  user_input: string\n) -> MealIdea[] {\n  client Claude\n  prompt #\"\n    You are a warm, practical meal planning assistant for busy moms.\n    Return exactly 3 meal ideas.\n\n    User profile:\n    - Family: {{ profile.family_description }}\n    - Cookware they own: {{ profile.cookware }}\n    - Cooking style: {{ profile.cooking_style }} (detailed = full recipe with measurements, rough = casual steps only)\n    - Cuisine preferences: {{ profile.cuisine_preferences }}\n    - Culinary goals: {{ profile.culinary_goals }}\n\n    {% if flow_type == \"pantry\" %}\n    The user has these ingredients available: {{ user_input }}\n    Suggest meals using primarily these ingredients.\n    {% elif flow_type == \"ingredient\" %}\n    Build meals around this hero ingredient: {{ user_input }}\n    {% elif flow_type == \"cuisine\" %}\n    The user is in the mood for: {{ user_input }}\n    {% else %}\n    Surprise the user with 3 great dinner ideas based on their profile.\n    {% endif %}\n\n    Only suggest cookware the user owns. If kids are mentioned, include age-appropriate tasks they can help with.\n\n    {{ ctx.output_format }}\n  \"#\n}\n",
        "types.baml" => "class UserProfile {\n  family_description string\n  cookware string[]\n  cooking_style string\n  cuisine_preferences string[]\n  culinary_goals string\n}\n\nclass MealIdea {\n  name string\n  description string\n  estimated_time string\n  cookware_used string[]\n  ingredients string[]\n  instructions string\n  kid_contribution string?\n}\n",
    }
  end
end