###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
# typed: false
require "sorbet-runtime"

require_relative "types"

module Baml
  
  module PartialTypes
    class MealIdea < T::Struct; end
    class UserProfile < T::Struct; end
    class MealIdea < T::Struct
      include Baml::Sorbet::Struct
      const :name, T.nilable(String)
      const :description, T.nilable(String)
      const :estimated_time, T.nilable(String)
      const :cookware_used, T::Array[T.nilable(String)]
      const :ingredients, T::Array[T.nilable(String)]
      const :instructions, T.nilable(String)
      const :kid_contribution, T.nilable(String)

      def initialize(props)
        super(
          name: props[:name],
          description: props[:description],
          estimated_time: props[:estimated_time],
          cookware_used: props[:cookware_used],
          ingredients: props[:ingredients],
          instructions: props[:instructions],
          kid_contribution: props[:kid_contribution],
        )

        @props = props
      end
    end
    class UserProfile < T::Struct
      include Baml::Sorbet::Struct
      const :family_description, T.nilable(String)
      const :cookware, T::Array[T.nilable(String)]
      const :cooking_style, T.nilable(String)
      const :cuisine_preferences, T::Array[T.nilable(String)]
      const :culinary_goals, T.nilable(String)

      def initialize(props)
        super(
          family_description: props[:family_description],
          cookware: props[:cookware],
          cooking_style: props[:cooking_style],
          cuisine_preferences: props[:cuisine_preferences],
          culinary_goals: props[:culinary_goals],
        )

        @props = props
      end
    end
  end
end